zacor_package::commands!("rand", {
    "int"                 => zr_rand::cmd_int,
    "float"               => zr_rand::cmd_float,
    "bool"                => zr_rand::cmd_bool,
    "word"                => zr_rand::cmd_word,
    "syllable"            => zr_rand::cmd_syllable [input],
    "name"                => zr_rand::cmd_name,
    "char"                => zr_rand::cmd_char,
    "uuid"                => zr_rand::cmd_uuid,
    "phrase"              => zr_rand::cmd_phrase,
    "pass"                => zr_rand::cmd_pass,
    "pattern"             => zr_rand::cmd_pattern,
    "color"               => zr_rand::cmd_color,
    "date"                => zr_rand::cmd_date,
    "pick"                => zr_rand::cmd_pick [input],
    "shuffle"             => zr_rand::cmd_shuffle [input],
    "character.archetype" => zr_rand::cmd_character_archetype,
    "character.motive"    => zr_rand::cmd_character_motive,
});
